#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
	mkdir "$HOME/Desktop/Tools"
	chown "$USER" "$HOME/Desktop/Tools"
fi
unzip "./HWMonitor.zip"
cp -Rf "./HWMonitor.app" "$HOME/Desktop/Tools/"
chown -R "$USER" "$HOME/Desktop/Tools/HWMonitor.app"
