#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
	mkdir "$HOME/Desktop/Tools"
	chown "$USER" "$HOME/Desktop/Tools"
fi
unzip "./Clover Configurator.zip"
cp -Rf "./Clover Configurator.app" "$HOME/Desktop/Tools/"
chown -R "$USER" "$HOME/Desktop/Tools/Clover Configurator.app"