#!/bin/bash

RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/L580CI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"

if [ ! -d /Volumes/EFI/EFI ]
then
	mounted=false;

	while read line; do
	mountpoint=`echo "$line" | awk -F'%' '{print substr($3, 4)}'`
	bsdname=`echo "$line" | awk '{print $1}'`
	efidevice=`diskutil list $bsdname | grep EFI | tr -s ' ' | awk '{print $NF}'`
	if [ "$mountpoint" = "${3}" -o "$mountpoint/" = "${3}" ]
	then
		case "$efidevice" in
		"")	echo "This drive $bsdname containing root has no EFI partition.";;
		*)	echo "Found EFI partition at /dev/$efidevice."
			if [ "`df -h | grep /dev/$efidevice`" != "" ]
			then
				diskutil unmount "/dev/$efidevice" && mkdir -p /Volumes/EFI && mount -t msdos "/dev/$efidevice" /Volumes/EFI
				echo "Mounted /dev/$efidevice at /Volumes/EFI."
			else
				mkdir -p /Volumes/EFI && mount -t msdos "/dev/$efidevice" /Volumes/EFI
			fi
			mounted=true;;

		esac
		break
	fi
	done < <(df -h | grep "/dev/")

	if ( ! $mounted )
	then
		while read line; do
			efidevice=`diskutil list $line | grep EFI | tr -s ' ' | awk '{print $NF}'`
			case "$efidevice" in
			"")	echo "This drive $line has no EFI partition.";;
			*)	echo "Found EFI partition at /dev/$efidevice."
				if [ "`df -h | grep /dev/$efidevice`" != "" ]
				then
					diskutil unmount "/dev/$efidevice" && mkdir -p /Volumes/EFI && mount -t msdos "/dev/$efidevice" /Volumes/EFI
					echo "Mounted /dev/$efidevice at /Volumes/EFI."
				else
					mkdir -p /Volumes/EFI && mount -t msdos "/dev/$efidevice" /Volumes/EFI
				fi
				break;;
			esac
		done < <(diskutil list | grep "/dev/")
	fi


fi

if [ -d /Volumes/EFI/EFI ]
then
	touch /Volumes/EFI/.metadata_never_index
	if [ ! -d "$BackupDir" ]
	then
		mkdir -p "$BackupDir"
		rsync -ar /Volumes/EFI/EFI "$BackupDir"
	fi
fi