#!/bin/bash
# rebilding the kext cache, if triggered
RebuildOn=`/usr/libexec/PlistBuddy -c "Print :KextCacheRebuild" /tmp/L580CI.plist`
if [ "$RebuildOn" == "yes" ]
then
    osxver=`/usr/libexec/PlistBuddy -c 'Print ProductVersion' "${3}"/System/Library/CoreServices/SystemVersion.plist`
    case $osxver in
    10.9*)	echo "OS X Mavericks $osxver detected."
                cd /Volumes/EFI/EFI/CLOVER/kexts/10.9/;;
    10.10*)	echo "OS X Yosemite $osxver detected."
                cd /Volumes/EFI/EFI/CLOVER/kexts/10.10/;;
    *)          echo "Unknown or unsupported OS X version, aborting.";;
    10.11*) echo "OS X El Capitan $osxver detected."
            cd /Volumes/EFI/EFI/CLOVER/kexts/10.11/;;
    *)      echo "Unknown or unsupported OS X version, aborting.";;
    esac

    for file in *.kext; do
        cp -rf $file /System/Library/Extensions/
        chmod -R 755 /System/Library/Extensions/$file
        chown -R root:wheel /System/Library/Extensions/$file
    done

    rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/BrcmPatchRAM.kext
    rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/BrcmPatchRAM.kext

    #diskutil repairPermissions /
	touch "${3}/System/Library/Extensions"
fi
# setting the Installer Backups folder's owner to the current user
if [ -e "$HOME/Desktop/Installer Backups" ]
then
	chown -R $USER "$HOME/Desktop/Installer Backups"
fi
# deleting temporary files
rm -rf /tmp/L580CI.plist
rm -rf /tmp/Apps
# enabling AirDrop
pmset -a hibernatemode 0

if [ -f /private/var/vm/sleepimage ]; then
    rm /private/var/vm/sleepimage
    rm -rf /private/var/vm/sleepimage
fi
if [ ! -d /private/var/vm/sleepimage ]; then
    mkdir /private/var/vm/sleepimage
fi

defaults write com.apple.NetworkBrowser BrowseAllInterfaces 1
#enabling Diskutility Debug to let users easier mount hidden partitions (e.g. the EFI partition)
defaults write com.apple.DiskUtility DUDebugMenuEnabled 1