#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
	mkdir "$HOME/Desktop/Tools"
	chown "$USER" "$HOME/Desktop/Tools"
fi
unzip "./MaciASL.zip"
cp -Rf "./MaciASL.app" "$HOME/Desktop/Tools/"
chown -R "$USER" "$HOME/Desktop/Tools/MaciASL.app"
