#!/bin/bash

RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/L580CI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"
osxver=`/usr/libexec/PlistBuddy -c 'Print ProductVersion' "${3}"/System/Library/CoreServices/SystemVersion.plist`



if [ ! -d /Volumes/EFI/EFI/CLOVER/kexts/10.10 ]
then
	mkdir -p /Volumes/EFI/EFI/CLOVER/kexts/10.10
fi

if [ ! -d /Volumes/EFI/EFI/CLOVER/kexts/10.11 ]
then
	mkdir -p /Volumes/EFI/EFI/CLOVER/kexts/10.11
fi

if [ ! -d /Volumes/EFI/EFI/CLOVER/kexts/10.12 ]
then
	mkdir -p /Volumes/EFI/EFI/CLOVER/kexts/10.12
fi

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/*
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.11/*

cp -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/* /Volumes/EFI/EFI/CLOVER/kexts/10.10
cp -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/* /Volumes/EFI/EFI/CLOVER/kexts/10.11
cp -rf /Volumes/EFI/EFI/CLOVER/kexts/10.11/* /Volumes/EFI/EFI/CLOVER/kexts/10.12

if [[ ! "$osxver" == 10.12* ]]
then
	rm -rf /System/Library/Extensions/USBInjectAll.kext
fi

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/AppleUSBXHCIPCIPortInjector.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/AppleUSBXHCIPCIPortInjector.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.11/AppleUSBXHCIPCIPortInjector.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.12/AppleUSBXHCIPCIPortInjector.kext

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.11/GenericUSBXHCI.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.12/GenericUSBXHCI.kext

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/BrcmPatchRAM2.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/BrcmPatchRAM2.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.11/BrcmPatchRAM.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.12/BrcmPatchRAM.kext

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/ALXEthernet.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/ALXEthernet.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.11/ALXEthernet.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.12/ALXEthernet.kext

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/EAPDFix.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/EAPDFix.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.11/EAPDFix.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.12/EAPDFix.kext

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/ACPIBacklight.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/ACPIBacklight.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.11/ACPIBacklight.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.12/ACPIBacklight.kext



systemsetup -setwakeonnetworkaccess off
/usr/libexec/PlistBuddy -c "Set :KextCacheRebuild yes" /tmp/L580CI.plist
