#!/bin/bash

RightNowIs=`/usr/libexec/PlistBuddy -c "Print :CurrentDateTime" /tmp/L580CI.plist`
BackupDir="$HOME/Desktop/Installer Backups/Backup $RightNowIs"


if [ ! -d /Volumes/EFI/EFI/CLOVER/kexts/10.10 ]
then
	mkdir -p /Volumes/EFI/EFI/CLOVER/kexts/10.10
fi

if [ ! -d /Volumes/EFI/EFI/CLOVER/kexts/10.11 ]
then
	mkdir -p /Volumes/EFI/EFI/CLOVER/kexts/10.11
fi

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/*
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.11/*

cp -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/* /Volumes/EFI/EFI/CLOVER/kexts/10.10
cp -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/* /Volumes/EFI/EFI/CLOVER/kexts/10.11

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/AppleUSBXHCIPCIPortInjector.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/AppleUSBXHCIPCIPortInjector.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.11/AppleUSBXHCIPCIPortInjector.kext

rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.9/BrcmPatchRAM2.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.10/BrcmPatchRAM2.kext
rm -rf /Volumes/EFI/EFI/CLOVER/kexts/10.11/BrcmPatchRAM.kext

systemsetup -setwakeonnetworkaccess off
/usr/libexec/PlistBuddy -c "Set :KextCacheRebuild yes" /tmp/L580CI.plist