#!/bin/bash
set -x

./BackupESP "$1" "$2" "$3"

if [ -d /Volumes/EFI/EFI ]
then
	rm /Volumes/EFI/EFI/Clover/drivers64UEFI/VBoxHfs*
	rm /Volumes/EFI/EFI/Clover/drivers64UEFI/OsxAptioFix2Drv-64.efi
	rm -rf /Volumes/EFI/EFI/CLOVER/themes/Universe
	rm -rf /Volumes/EFI/EFI/Boot/BOOTX64.efi
	rm -rf /Volumes/EFI/EFI/CLOVER/CLOVERX64.efi
fi

if [ -d /Library/Logs/CloverEFI ]
then
	rm -rf /Library/Logs/CloverEFI
fi

mkdir -p /Library/Logs/CloverEFI