#!/usr/bin/env bash
PKMKPIDFORAPP="./pkmkpidforapp"
PKMKSENDAE="./pkmksendae"

RESULT=`"$PKMKPIDFORAPP" 'com.apple.finder' 'Finder'`
if [ $RESULT -gt 0 ]; then
	RESULT=`"$PKMKSENDAE" $RESULT 'quit'`
fi

exit 0
