#!/bin/bash
if [ ! -r "$HOME/Desktop/Tools" ];
then
	mkdir "$HOME/Desktop/Tools"
	chown "$USER" "$HOME/Desktop/Tools"
fi
unzip "./Localtime-Toggle.pkg.zip"
cp -f "./Localtime-Toggle.pkg" "$HOME/Desktop/Tools/"
chown "$USER" "$HOME/Desktop/Tools/Localtime-Toggle.pkg"